project_id = "ivrwcmtjruvritolfpae"

[functions]
  [functions.admin-api]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat-assistant]
    verify_jwt = false
  [functions.generate-image]
    verify_jwt = false
  [functions.ai-tools-generate]
    verify_jwt = false
  [functions.generate-video]
    verify_jwt = false

