import { useState } from "react";
import { AIToolLayout } from "@/components/ai-tools/AIToolLayout";
import { useAIToolGenerator } from "@/hooks/useAIToolGenerator";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2, Copy, Plane } from "lucide-react";
import { SEOHead } from "@/components/SEOHead";

interface DayPlan { day: number; title: string; activities: { time: string; activity: string; tip: string }[]; }
interface Result { itinerary: DayPlan[]; budgetTips: string[]; travelTips: string[]; }

const AITravelPlanner = () => {
  const [destination, setDestination] = useState("");
  const [days, setDays] = useState("3");
  const [budget, setBudget] = useState("Medium");
  const { result, isLoading, generate, copyToClipboard } = useAIToolGenerator<Result>("travel-planner");

  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "AI Travel Planner", applicationCategory: "TravelApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };

  return (
    <AIToolLayout title="AI Travel Planner" metaTitle="AI Travel Planner — Smart Trip Itinerary" metaDescription="Plan your trip with AI. Get a daily itinerary, budget tips, and travel advice." canonical="/everyday-ai/travel-planner">
      <SEOHead title="AI Travel Planner" description="Plan trips with AI-powered itineraries" canonical="/everyday-ai/travel-planner" schema={schema} />
      <h1 className="text-3xl font-bold text-foreground mb-2 flex items-center gap-2"><Plane className="h-7 w-7 text-primary" /> AI Travel Planner</h1>
      <p className="text-muted-foreground mb-6">Get a detailed day-by-day travel itinerary with budget tips.</p>

      <div className="space-y-4 mb-8">
        <Input placeholder="Destination (e.g. Istanbul, Dubai)" value={destination} onChange={(e) => setDestination(e.target.value.slice(0, 200))} />
        <Input type="number" placeholder="Number of days" value={days} onChange={(e) => setDays(e.target.value)} min="1" max="30" />
        <Select value={budget} onValueChange={setBudget}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Low", "Medium", "High", "Luxury"].map(b => <SelectItem key={b} value={b}>{b}</SelectItem>)}</SelectContent></Select>
        <Button onClick={() => generate({ destination, days, budget })} disabled={isLoading || !destination.trim()} className="w-full">
          {isLoading ? <><Loader2 className="h-4 w-4 animate-spin mr-2" /> Planning...</> : "Plan My Trip"}
        </Button>
      </div>

      {result && (
        <div className="space-y-4">
          {result.itinerary?.map((day) => (
            <Card key={day.day}><CardContent className="pt-4">
              <h3 className="font-semibold text-foreground mb-2">Day {day.day}: {day.title}</h3>
              <div className="space-y-2">
                {day.activities.map((a, i) => (
                  <div key={i} className="bg-muted/30 p-2 rounded">
                    <p className="text-sm text-foreground"><span className="font-medium">{a.time}</span> — {a.activity}</p>
                    {a.tip && <p className="text-xs text-muted-foreground mt-1">💡 {a.tip}</p>}
                  </div>
                ))}
              </div>
            </CardContent></Card>
          ))}
          <Card><CardContent className="pt-4">
            <h3 className="font-semibold text-foreground mb-2">Budget Tips</h3>
            {result.budgetTips?.map((t, i) => <p key={i} className="text-sm text-muted-foreground">💰 {t}</p>)}
          </CardContent></Card>
          <Card><CardContent className="pt-4">
            <h3 className="font-semibold text-foreground mb-2">Travel Tips</h3>
            {result.travelTips?.map((t, i) => <p key={i} className="text-sm text-muted-foreground">✈️ {t}</p>)}
          </CardContent></Card>
          <Button variant="outline" onClick={() => copyToClipboard(JSON.stringify(result, null, 2))}><Copy className="h-3 w-3 mr-1" /> Copy Itinerary</Button>
        </div>
      )}

      <section className="mt-16 space-y-6">
        <h2 className="text-2xl font-bold text-foreground">AI-Powered Trip Planning</h2>
        <p className="text-muted-foreground">Get personalized travel itineraries with daily schedules, activity suggestions, and budget tips — all generated by AI in seconds.</p>
        <h2 className="text-xl font-bold text-foreground">FAQ</h2>
        <details className="border border-border rounded-lg p-4"><summary className="font-medium cursor-pointer">How accurate are the suggestions?</summary><p className="mt-2 text-sm text-muted-foreground">The AI provides helpful general guidance. Always verify specific details like opening hours and prices before your trip.</p></details>
      </section>
    </AIToolLayout>
  );
};

export default AITravelPlanner;
